### ISSUE TITLE
Yoshimi.rgd Expression CC should default to 127, not 100

### ISSUE THREAD

**Issue by tedfelix** [lorenzosu/rosegarden_yoshimi_banks#1] opened 2023-12-06 12:25 UTC
This was likely copied from an earlier version of rg which erroneously defaulted to 100 like volume.  To get expression completely out of the way, 127 is the correct default value.  The script that generates Yoshimi.rgd might need to be changed to make sure this is consistent from here on out.  I did not dig further.

`<control name="Expression" type="controller" description="&lt;none&gt;" min="0" max="127" default="127" controllervalue="11" colourindex="2" ipbposition="-1" />`

**Comment by lorenzosu** [comment] 2023-12-07 07:03
Yes an existing General Midi file was used as a model for the controllers XML as I couldn't find any documentation about it.

This is fixed in the latest master, where also the updated Yoshimi.rgd file has been pushed (and is also based on the lastest Yoshimi release which I intended to update anyway).
Please confirm if it works as expected now.

EDIT: had to re-open this manually waiting for feedback as github seems to automatically close issues where the issue is mentioned in the commit :-|

As a side note once this fix is confirmed I think I'll change some of those controllers and re-sort them or remove them from the panel as some just don't make sense with Yoshimi in the panel and their order is weird.

**Comment by tedfelix** [comment] 2023-12-29 14:16
I reviewed the .py script change and the new .rgd file.  Both look good.  Feel free to close.

**Comment by lorenzosu** [comment] 2023-12-29 16:49
Closing as per ted's report

**Closed as completed by lorenzosu** 2023-12-29 16:49 UTC
